# This is a basic workflow to help you get started with Actions

name: CD

on:
  push:
    branches:
      - main
      - dev
      - qa 
  pull_request:
    branches:
      - dev
      - qa
  workflow_dispatch:

jobs:
  test-before-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
          pip install ruff pytest

      - name: Run Ruff linting
        run: |
          echo "🔍 Running Ruff linting..."
          ruff check app tests

      - name: Run tests
        run: pytest tests --disable-warnings
