# This is a basic workflow to help you get started with Actions

name: CD

on:
  push:
    branches:
      - main
      - dev
      - qa 
  pull_request:
    branches:
      - dev
      - qa
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment: ${{ github.ref_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install system dependencies for Pillow
        run: |
          sudo apt-get update
          sudo apt-get install -y libjpeg-dev zlib1g-dev libpng-dev

      - name: Install Python dependencies
        run: pip install --upgrade pip && pip install -r requirements.txt

      - name: Run tests
        run: pytest tests --disable-warnings

      - name: Set environment variables
        run: |
          if [ "${{ github.ref_name }}" == "main" ]; then
            export APP_ENV="Prod"
            export APP_KEY="${{ secrets.PROD_API_KEY }}"
          elif [ "${{ github.ref_name }}" == "qa" ]; then
            export APP_ENV="QA"
            export APP_KEY="${{ secrets.QA_API_KEY }}"
          else
            export APP_ENV="Dev"
            export APP_KEY="${{ secrets.DEV_API_KEY }}"
          fi

          echo "🚀 Deploying to '${APP_ENV}'"
          echo "🔑 Using credentials for ${APP_ENV} (hidden)"

      - name: Deploy Streamlit app
        run: streamlit run app/main.py --server.port 8501 --server.headless true
