# This is a basic workflow to help you get started with Actions

name: CD

# Controls when the workflow will run
on:
  push:
    branches:
      - main
      - dev
      - qa 
  pull_request:
    branches:
      - dev
      - qa 
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    # Bind deployment to the GitHub Environment (Dev, QA, Prod)
    # This makes "Prod" require approval if configured in repo settings
    environment: ${{ github.ref_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install streamlit

      - name: Deploy to environment
        run: |
          if [ "${{ github.ref_name }}" == "main" ]; then
            export APP_ENV="Prod"
            export APP_KEY="${{ secrets.PROD_API_KEY }}"
          elif [ "${{ github.ref_name }}" == "qa" ]; then
            export APP_ENV="QA"
            export APP_KEY="${{ secrets.QA_API_KEY }}"
          else
            export APP_ENV="Dev"
            export APP_KEY="${{ secrets.DEV_API_KEY }}"
          fi

          echo "🚀 Deployed to '${APP_ENV}'"
          echo "🔑 Using credentials for ${APP_ENV} (hidden)"
