name: CI - Main / Prod

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt || true
          pip install pytest ruff

      - name: Run Ruff
        run: ruff check --output-format=github

      - name: Run Pytest (Prod)
        run: |
          mkdir -p tests
          pytest -m "prod" --junitxml=tests/results.xml

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: tests/results.xml

      - name: Ensure build artifacts exist
        run: |
          mkdir -p dist build
          echo "Dummy file" > dist/dummy.txt
          echo "Dummy file" > build/dummy.txt

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            dist/
            build/
