name: CI Prod Tests

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-mock

      - name: Run prod-only tests with JUnit XML output
        run: |
          pytest tests/ \
            -m prod \
            --junitxml=prod-test-report.xml \
            --tb=short

      - name: Upload test report artifact
        uses: actions/upload-artifact@v4
        with:
          name: prod-test-report
          path: prod-test-report.xml
